# Write your package code here!

# Variables exported by this module can be imported by other packages and
# applications. See sdui-tests.js for an example of importing.
export {
  userWithIdIsInRole, currentUserIsInRole,
  useCurrentUserIsInRole, currentUserMustBeInRole,
  scopesForUserWithIdInRole, scopesForCurrentUserInRole, useScopesForCurrentUserInRole
} from './common/roleChecks.coffee'
export {generateUUID} from './common/generateUUID.coffee'
export {useSession} from './common/useSession.coffee'
export {meteorApply} from './common/meteorApply.coffee'
export {config, useConfig, Configurations} from './config/config.coffee'
export {default as connectFieldWithLabel} from './forms/connectFieldWithLabel.coffee'
export {default as connectFieldPlus} from './forms/connectFieldPlus.coffee'
# export {SimpleSchema} from './api/setupSimpleSchema.coffee'
export {Schema} from './schema/Schema.coffee'
export {createTableDataAPI} from './api/createTableDataAPI.coffee'
export {createUserTableAPI} from './usertable/createUserTableAPI.coffee'
export {createQAArticlesAPI} from './qa-articles/createQAArticlesAPI.coffee'
export {createChatAPI, chatSchema} from './chat/createChatAPI.coffee'
export {createChatLogAPI, addCostsPipeline} from './chat/createChatLogAPI.coffee'
export {createAppLayoutAPI} from './app-layout/createAppLayoutAPI.coffee'

export {SdList} from './tables/SdList.coffee'
export {ActionButton} from './forms/ActionButton.coffee'
export {SdTable} from './tables/SdTable.coffee'
export {SdContentEditor} from './tables/SdContentEditor.coffee'
export {SdEditor} from './editor/SdEditor.coffee'
export {MarkdownDisplay} from './markdown/MarkdownDisplay.coffee'
export {ColorPicker} from './forms/ColorPicker.coffee'
export {ColorPickerField} from './forms/ColorPicker.coffee'
export {RatingField} from './forms/RatingField.coffee'
export {Thumbs} from './forms/ThumbsField.coffee'
export {ThumbsField} from './forms/ThumbsField.coffee'
export {ThumbsTableField} from './forms/ThumbsField.coffee'
export {LinkField} from './forms/LinkField.coffee'
export {LinkTableField} from './forms/LinkField.coffee'
export * from './forms/uniforms-custom/select-implementation'
export {ManagedForm} from './forms/ManagedForm.coffee'
export {FormModal} from './forms/FormModal.coffee'
export {LoginForm} from './login-forms/LoginForm.coffee'
export {LoginButton} from './login-forms/LoginButton.coffee'
export {FeedbackButton} from './forms/FeedbackButtonField.coffee'
export {FeedbackButtonField} from './forms/FeedbackButtonField.coffee'
export {FeedbackButtonTableField} from './forms/FeedbackButtonField.coffee'
export {SdDocumentSelect} from './tables/SdDocumentSelect.coffee'
export {SdDocumentSelectField} from './tables/SdDocumentSelect.coffee'
export {SdChat} from './chat/SdChat.coffee'
export {SdChat2} from './chat/SdChat2.coffee'
export {SdChatLog} from './chat/SdChatLog.coffee'
export {SdAppLayout} from './app-layout/SdAppLayout.coffee'
export {Gravatar} from './forms/GravatarField.coffee'
export {GravatarField} from './forms/GravatarField.coffee'
export {FormattedJSON} from './misc-components/FormattedJSON.coffee'
export {SdUserTable} from './usertable/SdUserTable.coffee'